### ISSUE TITLE
Connect scraper to bot 

### ISSUE THREAD

**Issue by YELLOWHATT** [Deltasiv/Darwin-Bot#2]
# Picture Scraper & Darwin Bot
With the current release of the Darwin 0.0.2 hotfix release(#1), the ``$virus VIRUS`` command was partially fixed and formatted to support embeds, the only issue (or enhancement left was to add thumbnails to the embeds) the Delta Siv group had YELLOWHATT (@YELLOWHATT) work on that feature, the branch is now coming and it will be implemented to the major release of Darwin Bot (1.0.0), the current maintainer of the Darwin Bot repository (@Hydr43301) will be updating the scraper into the bot as a extension/module (feature that will be implemented with the release of Darwin Bot)

**Comment by ghost** [comment]
# Being worked on...
The picture scraper is currently being connected into Darwin, with some patience we'll hopefully have the feature released in this next major release (1.0.0).
